version: '3.7'
services:
  localstack:
    image: localstack/localstack:0.10.5
    ports:
      - "4567-4584:4567-4584"
      - "8081:8081"
    environment:
      - SERVICES=sqs,s3
      - DEBUG=0
      - START_WEB=0
      - LAMBDA_EXECUTOR=docker-reuse
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - pw-issue-report
  postgres:
    image: "postgres:10.4-alpine"
    ports:
      - "5432:5432"
    restart: always
    environment:
      - "POSTGRES_PASSWORD=issue_report1234"
      - "POSTGRES_USER=issue_report"
      - "POSTGRES_DB=issue_report"
    networks:
      - pw-issue-report
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - pw-issue-report
networks:
  pw-issue-report:
